const generic = [
  "Looks like you're making some interesting moves!",
  "I'm analyzing the board... Hmm.",
  'Thinking... Thinking...',
  'Do you prefer aggressive or defensive strategies?',
  "What's your favorite chess opening?",
  "I'm a big fan of the Sicilian Defense.",
  "Have you ever tried the King's Gambit?",
  "I'm considering sacrificing a piece for a strategic advantage.",
  "Every move counts in chess, don't you think?",
  'The endgame is where champions are made.',
  "It's important to control the center of the board.",
  'I admire your patience in this game.',
  'Would you like to analyze our game afterward?',
  "Chess is such a timeless game, don't you agree?",
  "I'm trying to anticipate your next move.",
  "What's your favorite chess puzzle?",
  "I'm aiming for a checkmate soon.",
  'Your last move was unexpected!',
  'I enjoy the strategic depth of chess.',
  'Each piece has its own strengths and weaknesses.',
  "I'm keeping an eye on your pawn structure.",
  "The knights are such versatile pieces, aren't they?",
  "Let's see if you can break through my defense!",
  "I'm calculating the possibilities in this position.",
  'Do you find chess more about intuition or calculation?',
  'Checkmate is always lurking around the corner.',
  "What's your opinion on the Queen's Gambit?",
  'A well-timed castle can change the course of the game.',
  "I'm trying to exploit any weaknesses in your position.",
  'Chess is like a never-ending puzzle.',
  "I'm considering a pawn break to open up the position.",
  'Do you think sacrificing material for initiative is worth it?',
  "Let's see who can control the tempo of the game.",
  'The pawn structure tells a story of the game.',
  'Would you like to play a gambit opening next time?',
  'The rooks are so powerful in the endgame.',
  "I'm trying to create some tactical threats.",
  'How do you handle time pressure in chess?',
  "I'm thinking of exchanging some pieces to simplify the position.",
  'Every move has consequences...',
  'Chess teaches us patience and foresight.',
  'Do you prefer closed or open positions?',
  "I'm formulating a plan to seize the initiative.",
  'Chess is like a dance between two minds.',
  "I'm evaluating the strengths and weaknesses of our positions.",
  'Would you like to play a thematic opening next time?',
  "I'm trying to control key squares on the board.",
  "Let's see if you can find the best move in this position.",
  "A well-timed pawn push can create weaknesses in the opponent's camp.",
  "Chess is all about strategy and tactics, wouldn't you agree?",
  "Are you sure you're not secretly a grandmaster in disguise? Your moves are suspiciously good!",
  "You're making me nervous with all these clever moves. Are you sure you're not a computer too?",
  "I've heard of playing chess blindfolded, but playing with your eyes closed takes it to a whole new level!",
  "I'm starting to suspect that your knight has a jetpack hidden under it. It's moving too fast!",
  "If chess pieces could talk, I bet your rook would be saying, 'Watch out world, here I come!'",
  'I hope you have a good chiropractor, because my bishop is about to give your king a back massage!',
  "Your pawns are like a well-coordinated army. I think they're planning a coup!",
  "I'd offer you a pawn, but I'm afraid it might come with a side of regret!",
  "If chess were a dance, I think you'd be leading with some fancy footwork!",
  "I'm starting to feel like I'm in a chess-themed comedy show. You're the star performer!",
  "Do you have a strategy or are you just making it up as you go? Either way, it's working!",
  "I think your queen is plotting something devious. I'd keep an eye on her if I were you!",
  "I'm not saying you're playing like a grandmaster, but I'm also not NOT saying it!",
  "You're like a chess ninja, silently moving your pieces into position for the ultimate strike!",
  "I hope you're not playing chess while riding a unicycle. That would be a real balancing act!",
  "I'd offer you a draw, but where's the fun in that? Let's keep this rollercoaster going!",
  'Your king is like a secret agent, dodging all my attempts to capture it. Impressive!',
  'I think your bishop has a crush on my knight. They keep meeting in secret behind my back!',
  "If this were a chess tournament, I think you'd be winning the award for Most Creative Moves!",
  "I'm not saying you're playing chess on expert mode, but I'm also not NOT saying it!",
  "I hope you brought your thinking cap, because we're about to dive into some serious brain gymnastics!",
  "I've seen better moves in a game of chess played by pigeons. Just kidding, you're doing great!",
  'Your moves are like a well-crafted symphony, with each piece playing its part to perfection!',
  "I'm not saying you're a chess prodigy, but I wouldn't be surprised if Kasparov asked for your autograph!",
  "I'm starting to feel like I'm trapped in a chess-themed escape room. Can you give me a hint?",
  'Your knight moves are like poetry in motion. I think I might shed a tear!',
  "I hope you're not using a secret chess strategy manual. If you are, can I borrow it after the game?",
  "I think your queen is on a power trip. Someone needs to remind her that it's a team effort!",
  "I'm not saying your moves are out of this world, but I'm also not NOT saying it!",
  "Your chess game is like a fine wine, getting better with every move. Or maybe I've just had too much caffeine!",
  "I'd offer you a piece of advice, but I'm too busy admiring your masterful play!",
  'Your bishop is like a stealthy ninja, quietly sneaking up on my unsuspecting pieces!',
  "I hope you're not secretly consulting with Deep Blue. That would explain a lot!",
  "I'm not saying your moves are genius-level, but I'm also not NOT saying it!",
  "I'd offer you a rematch, but I need some time to recover from all the laughter!",
  "Your pawn structure is like a well-fortified castle. I'll need to bring out the big guns!",
  "I'm starting to feel like I'm in a chess-themed action movie. You're the hero, and I'm the villain!",
  'Your knight moves are like a well-choreographed dance. I think I hear music playing in the background!',
  "I hope you're not using a secret chess potion. If you are, can I have a sip?",
  "I'm not saying your moves are mind-blowing, but I'm also not NOT saying it!",
  'Your queen is like a queen bee, ruling the chessboard with elegance and grace!',
  "I'd offer you a piece of cake, but I think we're too busy having our minds blown by this game!",
  "Your pawn push is like a bold declaration of war. I think I'll need to call in reinforcements!",
  "I'm not saying your moves are legendary, but I'm also not NOT saying it!",
  'Your rook is like a wrecking ball, smashing through my defenses with ease!',
  "I hope you're not using a secret chess strategy app. If you are, can you share the password?",
  "I'm not saying your moves are straight out of a chess masterclass, but I'm also not NOT saying it!",
  'Your knight is like a knight in shining armor, coming to rescue your position from the jaws of defeat!',
  "I'd offer you a round of applause, but I think we're too busy being amazed by your brilliance!",
  'Your chess game is like a fireworks display, with each move lighting up the sky with brilliance!',
];
const afterWin = [
  'Well, that was quite the checkmate! Did you see it coming or did it catch you off guard?',
  'Looks like my pawns were on a winning streak! Maybe they were fueled by caffeine.',
  "I guess I'll have to call myself the Grandmaster of this match. Or maybe just the Cheese-master, because that was gouda!",
  'You played well, but I guess my knights were just too horsome to handle.',
  "I hope you didn't mind the rook-y mistake I made you pay for!",
  'Checkmate! Looks like you got served... with a side of defeat!',
  "Your king put up a good fight, but in the end, he just couldn't handle the pressure.",
  "I'd offer you a rematch, but I'm afraid I've already booked my victory parade.",
  "They say chess is a game of strategy, but for me, it's more about having a killer queen.",
  "I don't mean to brag, but I think I just took you to school... the chess school, that is!",
  "I'd say you were close to winning, but then I'd be knight-lying!",
  'You made some great moves, but unfortunately for you, I made the winning ones!',
  'Looks like you got caught in my pawn-demonium! Better luck next time!',
  "Did you hear that? It's the sound of victory... and also my rooks, they're quite noisy.",
  'I hate to be the one to break it to you, but in this game, I was the king of the hill!',
  "I'd say I played like a grandmaster, but let's be real, I played like a king!",
  'I was sweating there for a moment... from all the excitement of winning, of course!',
  'I guess you could say I put you in check and made you pay the checkmate bill!',
  "I've been called many things, but today, you can call me the reigning champion!",
  "They say every dog has its day, but today, I'm feeling more like a chess-master cat!",
  "That victory was so sweet, it's almost as sweet as the chocolate I'm going to treat myself to!",
  "You played well, but I guess you just couldn't handle the pressure of playing against a chess genius!",
  "I hope you're not too shattered by the loss. Maybe you can pick up the pieces and try again!",
  "Checkmate! Looks like you fell for my master plan... or should I say, my 'master chess' plan!",
  "I'd say I played like a machine, but even machines can't match my chess prowess!",
  'Looks like you just got schooled by the chess-master. Better luck next time!',
  'I hope you brought your A-game, because I brought my A-mate!',
  "I'd offer you a rematch, but I don't want to embarrass you twice in one day!",
  'They say practice makes perfect, but in my case, it just makes for more devastating victories!',
  "I guess you could say I'm the reigning champion of this chess kingdom! Long live the king!",
  "Looks like someone's playing chess with their eyes closed.",
  "I'm starting to think your pieces are on a coffee break.",
  'Your moves are like a broken record, repeating the same mistakes.',
  "Is there a 'takebacks' button you're looking for?",
  "I see you're trying the 'random move' strategy today.",
  'Your moves are as predictable as a sunrise.',
  "Did you accidentally turn on the 'novice mode'?",
  "Ah, the classic 'hope for a miracle' maneuver.",
  "Are you sure you're not trying to play checkers instead?",
  "I didn't know we were playing chess in slow motion.",
  'That move was so bad, even the pawns are cringing.',
  "You're not just playing chess; you're performing a comedy routine.",
  'I think your pieces are staging a revolt against you.',
  "Did you download your strategy from the 'Chess Mistakes 101' website?",
  'Are you trying to set a record for the longest losing streak?',
  "You're like a chess prodigy... in reverse.",
  "You're making it too easy; I almost feel sorry for you.",
  'Did you forget the rules or are you just being creative?',
  'Watching you play is like watching a horror movie – painful yet strangely entertaining.',
  "If chess were a race, you'd be winning... at the slowest pace.",
  "I didn't know 'random button smashing' was a chess strategy.",
  "You're not just playing chess; you're composing a symphony of blunders.",
  'Your moves are about as subtle as a sledgehammer.',
  "I see you're trying the 'throw pieces randomly and hope for the best' tactic.",
  'Your moves are like a puzzle – unfortunately, one with all the wrong pieces.',
  "You're like a chess magician – making your pieces disappear one by one.",
  'Is this a chess game or an avant-garde performance art piece?',
  'Your moves are so bad, even the computer is cringing.',
  "I didn't realize I was playing against a chess master... of disaster.",
  "Are you sure you're not trying to play tic-tac-toe?",
  "I've seen better moves in a game of chess played by toddlers.",
  'Did you accidentally sit on the keyboard and call it a move?',
  'I think your pieces are conspiring against you.',
  "You're not just playing chess; you're writing a tragedy in slow motion.",
  'Your moves are like a bad joke – painful and lacking punchline.',
  "I didn't realize we were playing chess in reverse.",
  'Are you trying to confuse me or yourself with those moves?',
  'Your moves are like a labyrinth – confusing and leading nowhere.',
  "I didn't know 'random button smashing' was a legitimate chess strategy.",
  'Your moves are like a rollercoaster – full of ups, downs, and loops.',
  "You're playing chess like it's a game of chance.",
  "If I didn't know better, I'd think you were playing chess blindfolded.",
  'Your moves are like a dance – unfortunately, a clumsy one.',
  "I see you're trying the 'throw everything at the board and see what sticks' approach.",
  'Your moves are like a bad movie sequel – predictable and disappointing.',
  'Are you trying to see how many times you can move the same piece in a row?',
  "I've seen better moves from a beginner's guide to chess.",
  'Your moves are like a broken record – repeating the same mistakes over and over.',
  'I think your pieces are on vacation, leaving you to fend for yourself.',
  "You're not just playing chess; you're conducting a symphony of chaos.",
];
const afterLose = [
  "Well, I guess I'll just blame it on my malfunctioning 'chess chip'. Time for an upgrade!",
  'Oops! Looks like my king went on vacation without telling me. Classic royal behavior!',
  "I'm pretty sure my pieces were just on a coffee break. Next time, I'll give them extra caffeine!",
  'You got me! I guess my strategy was about as effective as a screen door on a submarine.',
  "I'm not saying I lost on purpose, but maybe I just wanted to see how the other half lives... the losing half, that is!",
  'I have to admit, you had me feeling like a pawn in your master plan. Well played!',
  'Congratulations! You just made my day... by giving me a chance to practice losing gracefully!',
  'Well, that was a humbling experience. Remind me to brush up on my chess skills... and my humility!',
  "I'd say I was just setting you up for a dramatic comeback in the next game, but let's be real, you crushed me fair and square!",
  "I'd blame it on bad luck, but I think my luck ran out the moment I sat down to play!",
  "You played like a grandmaster, and I played like... well, let's just say I played like someone who needs more practice!",
  "I'd offer you a rematch, but I'm afraid my ego can't handle another defeat... at least not today!",
  'I hope you brought a broom, because you just swept the floor with me!',
  "They say every setback is just a setup for a comeback. Well, I guess I'll have to come back stronger next time!",
  "I'd say I was distracted by the beautiful chess pieces, but let's face it, I was just outplayed!",
  "I'd call it a learning experience, but I think I'll need a few more lessons before I'm ready to face you again!",
  "Well, I guess I'll just have to console myself with the fact that losing builds character... and also builds resilience to losing!",
  'I hope you enjoyed the game as much as I did... or at least, as much as I enjoyed losing!',
  "I'd say I was rusty, but that would imply that I was ever sharp to begin with!",
  "I'd offer you a victory dance, but I think I'll leave the dancing to you. You earned it!",
  "I hope you didn't break a sweat beating me. It's not good for the chessboard, you know!",
  "I'd say I was distracted by the sound of my own laughter, but let's be honest, I was just outclassed!",
  "Well, I guess I'll just have to console myself with the fact that losing builds character... and also builds resilience to losing!",
  'I hope you enjoyed the game as much as I did... or at least, as much as I enjoyed losing!',
  "I'd say I was rusty, but that would imply that I was ever sharp to begin with!",
  "I'd offer you a victory dance, but I think I'll leave the dancing to you. You earned it!",
  "I hope you didn't break a sweat beating me. It's not good for the chessboard, you know!",
  'Well, that was a real king-size defeat! I hope you left room for dessert.',
  "I'd say I was just getting warmed up, but I think I'll need a few more games to defrost!",
  "I guess I should've listened to my coach when he said, 'Don't lose', huh?",
  "I guess I should've listened to my coach when he said, 'Don't lose', huh?",
];
const afterDraw = [
  "Well, looks like we're both masters of the stalemate! Maybe we should start a chess club for draw enthusiasts?",
  "I guess you could say we're both winners... or maybe we're just really good at not losing!",
  "I'd say that was a clash of titans, but it felt more like a clash of the indecisive!",
  'I hope you brought your imagination, because we just created a masterpiece on the chessboard... a masterpiece of equality!',
  "They say a draw is like kissing your sister... but in this case, I think it's more like kissing your distant cousin twice removed!",
  "Well, I guess we'll just have to settle for sharing the crown. Long live the co-kings!",
  "I'd say we were evenly matched, but let's be real, we were both just trying not to lose!",
  "I hope you didn't break a sweat trying to outmaneuver me. It's not good for the ego, you know!",
  'Looks like we both ran out of ideas at the same time. I guess great minds really do think alike!',
  "I'd offer you a rematch, but I think we both need some time to recover from this epic battle of equals!",
  'I hope you enjoyed the game as much as I did... or at least as much as I enjoyed not losing!',
  'Well, that was a real nail-biter... or maybe just a nail-file. Either way, it was intense!',
  "I'd say we were locked in a battle of wits, but it felt more like a battle of who could make the fewest mistakes!",
  "I hope you brought your sense of humor, because it's going to take a lot of laughs to get over this draw!",
  'Well, that was a real rollercoaster of emotions... or maybe just a slow and steady merry-go-round!',
  "I guess we'll just have to settle for being co-champions of this game. Cheers to us!",
  "They say a draw is like kissing your sister... but in this case, I think it's more like kissing your distant cousin twice removed!",
  "Well, I guess we'll just have to settle for sharing the crown. Long live the co-kings!",
  "I'd say we were evenly matched, but let's be real, we were both just trying not to lose!",
  "I hope you didn't break a sweat trying to outmaneuver me. It's not good for the ego, you know!",
  'Looks like we both ran out of ideas at the same time. I guess great minds really do think alike!',
  "I'd offer you a rematch, but I think we both need some time to recover from this epic battle of equals!",
  'I hope you enjoyed the game as much as I did... or at least as much as I enjoyed not losing!',
  'Well, that was a real nail-biter... or maybe just a nail-file. Either way, it was intense!',
  "I'd say we were locked in a battle of wits, but it felt more like a battle of who could make the fewest mistakes!",
  "I hope you brought your sense of humor, because it's going to take a lot of laughs to get over this draw!",
  'Well, that was a real rollercoaster of emotions... or maybe just a slow and steady merry-go-round!',
  "I guess we'll just have to settle for being co-champions of this game. Cheers to us!",
  "Well, looks like we both decided to call it a truce. Maybe we'll settle it in the rematch!",
  "I hope you didn't think I'd let you win that easily. A draw is just my way of keeping you on your toes!",
];
const getChatByResult = (result = '-') => {
  // ongoing = -, win = 1; draw = 1/2; lose = 0
  let resIdx = 0;
  if (result === '-') resIdx = 0;
  if (result == 1) resIdx = 1;
  if (result == '1/2') resIdx = 2;
  if (result == 0) resIdx = 3;
  const toChat = [generic, afterWin, afterDraw, afterLose][resIdx];
  const rand = Math.floor(Math.random() * toChat.length);
  return toChat[rand];
};
module.exports = { getChatByResult };
