/**
 * Game subscribes to gameId events and handles them posting moves
 * generated by player object that must implement two methods:
 *
 * getNextMove(array of uciMoves) returns uciMove
 * getReply(chat event) returns chat message
 *
 */

// depth 8
// depth 4~6 = ELO 2100~2200
// depth 4~ = 1900
// depth 2 = ELO 1600~1700 // can't mate simple KRK Endgame

const { spawn } = require('child_process');

const STOCKFISH_PATH =
  'src/stockfish-windows-x86-64-avx2 (Stockfish 16)/stockfish/stockfish-windows-x86-64-avx2.exe';
const LC0_PATH = 'src/lc0-v0.30.0-windows-gpu-nvidia-cudnn/lc0.exe';

const { getMoveBaseOnMovesHistory } = require('./utils/my_openings.js');
const { getChatByResult } = require('./utils/randomChat.js');

const allowanceTime = 2000;
const minMaxMoveTime = () => {
  return 3000 + Math.floor(Math.random() * 8000);
};

class Game {
  /**
   * Initialise with interface to lichess.
   */
  constructor(api, name, player) {
    this.api = api;
    this.name = name;
    this.player = player;
    this.stockfish = spawn(LC0_PATH);
    this.variant = 'standard';
    this.initialFen = 'startpos';
    this.ponderMove = '';
    this.maxDepth = null;
    this.waitToIgnoreLastMove = false;

    this.stockfish.stdout.on('data', (data) => {
      const message = String(data);
      if (message.includes('bestmove')) {
        const bestmoveIndex = message.indexOf('bestmove');
        let bestMove = message.slice(bestmoveIndex + 9, bestmoveIndex + 13);
        this.ponderMove = message.slice(bestmoveIndex + 21, bestmoveIndex + 25);
        // if ()
        if (bestmoveIndex !== -1) {
          if (this.waitToIgnoreLastMove) {
            // ignore listened bestmove
            this.ponderMove = '';
            this.waitToIgnoreLastMove = false;
            this.engineMove();
          } else {
            // apply bestMove
            this.api.makeMove(this.gameId, bestMove);
            // pondering
            const { wtime, btime, winc, binc, moves } = this.gameProps;
            // console.log('STOCKFISH message:', message);
            if (this.ponderMove) {
              this.uciPost(
                `position ${this.initialFen} moves ${moves} ${bestMove} ${this.ponderMove}`,
              );
              this.uciPost(
                `go ponder wtime ${wtime} btime ${btime} winc ${winc} binc ${binc}${this.maxDepth ? ' depth ' + this.maxDepth : ''}`,
              );
            } else {
            }
          }
        }
      }
      const mate = message.match(/mate (-*\d+)/);
      // if (mate) {
      //   // this.api.chat(
      //   //   this.gameId,
      //   //   'player',
      //   //   `I saw mate in mate in ${mate[1]}, you better resign now. LOL`,
      //   // );
      // }
    });

    // Handle errors
    this.stockfish.on('error', (error) => {
      console.error(`Error starting Stockfish: ${error.message}`);
    });
    this.stockfish.on('exit', (error) => {
      console.error(`Stockfish Error: ${error}`);
    });
  }

  start(gameId) {
    this.gameId = gameId;
    this.api.streamGame(gameId, (event) => this.handler(event));
  }

  uciInit() {
    this.uciPost('uci');
    if (this.variant === 'chess960') {
      this.uciPost('setoption name UCI_Chess960 value true');
    }
    this.uciPost('isready');
    this.uciPost('ucinewgame');
    this.uciPost('setoption name Threads value 1');
    this.uciPost('setoption name Hash value 1024');
    this.uciPost('setoption name multipv value 1');
    // this.uciPost('setoption name Ponder value true');
    // this.uciPost('setoption name Skill Level value 5');
    // this.uciPost('setoption name UCI_LimitStrength true');
    // this.uciPost('setoption name UCI_Elo value 1320');
    this.uciPost('setoption name Use NNUE value true');
    this.uciPost('setoption name Move Overhead value 1000');
    this.uciPost('setoption name MoveOverheadMs value 1000');
  }

  handleChatLine(event) {
    if (event.username !== this.name) {
      const chatMessage = [
        'Hello, world!',
        'I can think 4-7 moves ahead. I am strong in tactical motifs, but weak in positional play during the middle game. Sadge T_T. ',
        'You can easily beat me if you outplay me in the middle game and convert your positional advantage to the endgame.',
        'But be careful, as I rarely make blunder moves just because of your obvious tricks and tactics. LOL.',
        'If I am offline or not making a move, you can contact Chester Agsamosam on his messenger. Thank you.',
      ];
      for (let i = 0; i < chatMessage.length; i++) {
        setTimeout(
          () => {
            this.api.chat(this.gameId, event.room, chatMessage[i]);
          },
          i * 1000 + i * 2000,
        );
      }
    }
  }

  uciPost(uciCmd) {
    // console.log('>>>>>>>>>>>>>>>>>>UCI Command:', uciCmd);
    this.stockfish.stdin.write(`${uciCmd}\n`);
  }

  engineMove() {
    const { wtime, btime, winc, binc, moves } = this.gameProps;
    const myTime = this.colour === 'white' ? wtime : btime;
    // const myInc = this.colour === 'white' ? winc : binc;
    const timeToMove = minMaxMoveTime();
    // const timeToMove = 2000;
    const timeControl = `wtime ${wtime} btime ${btime} winc ${winc} binc ${binc}`;
    const haveMyOpenings =
      this.variant === 'standard' &&
      getMoveBaseOnMovesHistory(moves, this.colour);
    if (haveMyOpenings) {
      this.api.makeMove(this.gameId, haveMyOpenings);
    } else if (moves === '' && this.colour === 'white') {
      this.api.makeMove(this.gameId, 'e2e4');
    } else {
      this.uciPost(
        `position ${this.initialFen}${moves ? ' moves ' + moves : ''}`,
      );
      let toPost = `go ${timeControl}${this.maxDepth ? ' depth ' + this.maxDepth : ''}`;
      // if (myTime > timeToMove + allowanceTime && moves.length > 20) {
      //   setTimeout(() => {
      //     this.uciPost(toPost);
      //   }, timeToMove);
      // } else {
      //   this.uciPost(toPost);
      // }
      this.uciPost(toPost);
      // console.log('timeToMove', timeToMove);
      // console.log(toPost);
      // if (moves.length > 100 || !myInc) {
      //   this.uciPost(`go ${timeControl}`);
      // } else {
      // }
    }
  }

  handler(event) {
    switch (event.type) {
      case 'chatLine':
        this.handleChatLine(event);
        break;
      case 'gameFull':
        this.colour = this.playingAs(event);
        this.gameProps = event.state;
        if (event.initialFen !== 'startpos')
          this.initialFen = 'fen ' + event.initialFen;
        this.variant = event.variant.key;
        this.uciInit();
        if (this.isTurn(this.colour, event.state.moves)) {
          this.engineMove();
        }
        break;
      case 'gameState':
        const { moves } = event;
        this.gameProps = event;
        let lastMove = moves.slice(moves.length - 4);
        if (this.isTurn(this.colour, moves)) {
          if (event.status === 'started') {
            if (this.ponderMove === lastMove) {
              this.uciPost('ponderhit');
            } else {
              if (this.ponderMove) {
                this.uciPost('stop');
                this.waitToIgnoreLastMove = true;
              } else {
                this.engineMove();
              }
            }
          }
        }
        break;
      case 'gameFinish':
        let haveWinner = event.game ? event.game.winner : '';
        if (haveWinner) {
          if (event.game.winner === this.colour) {
            this.api.chat(this.gameId, 'player', getChatByResult(1));
          } else {
            this.api.chat(this.gameId, 'player', getChatByResult(0));
          }
        } else {
          this.api.chat(this.gameId, 'player', getChatByResult('1/2'));
        }
        break;
      default:
        this.uciPost('stop');
        this.uciPost('quit');
        console.log('Unhandled game event : ' + JSON.stringify(event));
    }
  }

  playNextMove(previousMoves) {
    const moves = previousMoves === '' ? [] : previousMoves.split(' ');
    if (this.isTurn(this.colour, moves)) {
      const nextMove = this.player.getNextMove(moves);
      if (nextMove) {
        console.log(this.name + ' as ' + this.colour + ' to move ' + nextMove);
        this.api.makeMove(this.gameId, nextMove);
      }
    }
  }

  playingAs(event) {
    return event.white.name === this.name ? 'white' : 'black';
  }

  isTurn(colour, moves) {
    const movesArr = moves === '' ? [] : moves.split(' ');
    const parity = movesArr.length % 2;
    return colour === 'white' ? parity === 0 : parity === 1;
  }
}

module.exports = Game;
